<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Aktifitasakun extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aktifitasakun_model');
        $this->load->library('form_validation');
        set_timezone();
    }

    public function index($akunlevel)
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'user/Aktifitasakun/index/'.$akunlevel.'?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'user/Aktifitasakun/index/'.$akunlevel.'?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'user/Aktifitasakun/index/'.$akunlevel.'';
            $config['first_url'] = base_url() . 'user/Aktifitasakun/index/'.$akunlevel.'';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        switch (strtolower($akunlevel)) {
            case 'petugas':
                $config['total_rows'] = $this->Aktifitasakun_model->total_rows_join_akunpetugas($q);
                $aktifitasakun = $this->Aktifitasakun_model->get_limit_data_join_akunpetugas($config['per_page'], $start, $q);
                break;
            default:
                $config['total_rows'] = $this->Aktifitasakun_model->total_rows_join_akunpelanggan($q);
                $aktifitasakun = $this->Aktifitasakun_model->get_limit_data_join_akunpelanggan($config['per_page'], $start, $q);
                break;
        }

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'aktifitasakun_data' => $aktifitasakun,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'akunlevel'=>$akunlevel,
            'judul' => array("Aktifitas Akun", $akunlevel),
            'konten' => "user/aktifitasakun/aktifitasakun_list",
            'per_page' => $config['per_page']
        );
        $this->load->view('user/container', $data);
    }

    public function read($id) 
    {
        $row = $this->Aktifitasakun_model->get_by_id($id);
        if ($row) {
            $data = array(
		'token' => $row->token,
		'idakun' => $row->idakun,
		'datavalue' => $row->datavalue,
		'displaytext' => $row->displaytext,
		'controller' => $row->controller,
		'action' => $row->action,
		'tanggal' => $row->tanggal,
		'jam' => $row->jam,
	    );
            $this->load->view('aktifitasakun/aktifitasakun_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('aktifitasakun'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('idakun', 'idakun', 'trim|required');
	$this->form_validation->set_rules('datavalue', 'datavalue', 'trim|required');
	$this->form_validation->set_rules('displaytext', 'displaytext', 'trim|required');
	$this->form_validation->set_rules('controller', 'controller', 'trim|required');
	$this->form_validation->set_rules('action', 'action', 'trim|required');
	$this->form_validation->set_rules('tanggal', 'tanggal', 'trim|required');
	$this->form_validation->set_rules('jam', 'jam', 'trim|required');

	$this->form_validation->set_rules('token', 'token', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Aktifitasakun.php */
/* Location: ./application/controllers/Aktifitasakun.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-22 10:55:12 */
/* http://harviacode.com */