<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengeluaran_model extends CI_Model
{

    public $table = 'pengeluaran';
    public $id = 'idpengeluaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all_join_petugas()
    {
        $this->db->select("*");
        $this->db->join('petugas', $this->table.".idakun = petugas.idakun");
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id_join_petugas($id)
    {
        $this->db->select("*");
        $this->db->join('petugas', $this->table.".idakun = petugas.idakun");
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idpengeluaran', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('pengeluaran', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('idakun', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    
    // get total rows
    function total_rows_join_petugas($q = NULL) {
        $this->db->select("*");
        $this->db->from($this->table);
        $this->db->join('petugas', $this->table.".idakun = petugas.idakun");
        $this->db->like('idpengeluaran', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('pengeluaran', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like($this->table.'.idakun', $q);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_data_join_petugas($q = NULL) {
        $this->db->select("*");
        $this->db->join('petugas', $this->table.".idakun = petugas.idakun");
        $this->db->like('idpengeluaran', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('pengeluaran', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like($this->table.'.idakun', $q);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data with limit and search
    function get_limit_data_join_petugas($limit, $start = 0, $q = NULL) {
        $this->db->select("*");
        $this->db->join('petugas', $this->table.".idakun = petugas.idakun");
        $this->db->like('idpengeluaran', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('pengeluaran', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like($this->table.'.idakun', $q);
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idpengeluaran', $q);
    	$this->db->or_like('deskripsi', $q);
    	$this->db->or_like('pengeluaran', $q);
    	$this->db->or_like('tgl', $q);
        $this->db->or_like('idakun', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pengeluaran_model.php */
/* Location: ./application/models/Pengeluaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-22 10:55:14 */
/* http://harviacode.com */